### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by alecsio** [gandrewstone/LIN#1]
Hi, I tried your code but it keeps giving me this error when compiling:    fatal error: lightuino5.h: No such file or directory
Help please

**Comment by gandrewstone** [comment]
try commenting that include out. Its just the board that I developed this
on because it had a free serial.  But otherwise it should not be necessary
-- there is nothing board-specific about LIN.

**Comment by alecsio** [comment]
Hi, thank you for the fast response,
after commenting that include , fatal error: WProgram.h: No such file or directory apears,
I also commented this but then pandora opened :))

In file included from sketch\lin.h:36:0, from sketch\lin.cpp:4: sketch\heapskew.h: In member function 'T\* HeapSkew<T>::merge(T_, T_)':
heapskew.h:117: error: 'byte' was not declared in this scope
   byte SizeCtr=0;
heapskew.h:117: error: expected ';' before 'SizeCtr'
   byte SizeCtr=0;
heapskew.h:133: error: 'SizeCtr' was not declared in this scope
     SizeCtr++;
heapskew.h:136: error: 'SizeCtr' was not declared in this scope
  DepthLastOp = SizeCtr;
In file included from sketch\lin.cpp:4:0:
Sketch\lin.h: In member function 'void Lin::add(LinScheduleEntry&, uint16_t)':
lin.h:122: error: 'millis' was not declared in this scope
   void add(LinScheduleEntry& entry,uint16_t when=0) { entry.trigger = millis() + when; scheduler.push(entry); }
sketch\lin.cpp: In member function 'void Lin::loop()':
lin.cpp:27: error: 'millis' was not declared in this scope
  if ((&e)&&(e.trigger < millis()))
sketch\lin.cpp: In member function 'void Lin::serialBreak()':
lin.cpp:62: error: 'OUTPUT' was not declared in this scope

   pinMode(txPin, OUTPUT);
lin.cpp:62: error: 'pinMode' was not declared in this scope
   pinMode(txPin, OUTPUT);
lin.cpp:63: error: 'LOW' was not declared in this scope
   digitalWrite(txPin, LOW);  // Send BREAK
lin.cpp:63: error: 'digitalWrite' was not declared in this scope
   digitalWrite(txPin, LOW);  // Send BREAK
lin.cpp:65: error: 'HIGH' was not declared in this scope
   digitalWrite(txPin, HIGH);  // BREAK delimiter
sketch\lin.cpp: In member function 'uint8_t Lin::recv(uint8_t, uint8_t*, uint8_t, uint8_t)':
lin.cpp:114: error: 'INPUT' was not declared in this scope
   pinMode(txPin, INPUT);
 lin.cpp:114: error: 'pinMode' was not declared in this scope
   pinMode(txPin, INPUT);
lin.cpp:115: error: 'LOW' was not declared in this scope
 digitalWrite(txPin, LOW);  // don't pull up
lin.cpp:115: error: 'digitalWrite' was not declared in this scope
   digitalWrite(txPin, LOW);  // don't pull up
lin.cpp:142: error: 'OUTPUT' was not declared in this scope
pinMode(txPin, OUTPUT);
exit status 1
'byte' was not declared in this scope
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by gandrewstone** [comment]
arg!  WProgram.h has been renamed to Arduino.h:  https://github.com/adafruit/DHT-sensor-library/issues/1

I probably need to update this project, but my LIN hardware setup has long since been disassembled. :-(  If you keep at it, I'll keep helping

**Comment by alecsio** [comment]
Ok, edited to Arduino.h but I keep getting compiling error . What version of arduino did you use ?

**Comment by gandrewstone** [comment]
I forget :-(.  It was pre-1.0

**Comment by alecsio** [comment]
I tried your code on  Arduino 0023 , 1.0.6, 1.6.0 , 1.6.4 and 1.6.6 but unfortunately I still have errors :(

**Comment by gandrewstone** [comment]
Ok that kind of motivation deserves some help!  I have Arduino 1.6.5 installed here so I resolved all the compilation issues on that version.  I think that you'll find any 1.6.x version compiles fine now (probably any 1.0+ version).  I wasn't able to test it though because like I said my LIN test harness is in a box in the closet.  What is your project?  If you need to discuss privately we can email...

**Comment by alecsio** [comment]
Yes , thank you , now all works fine  :)  I changed the headlights on my Opel Insignia / Buick Regal with the facelift ones but GM changed the control codes . I am trying to create a sniffer and make them work again . It's also a hobby but unfortunately my low knowledge in C slows me a bit . my address is aionescu[at]kepler.ro

**Comment by gandrewstone** [comment]
awesome! good luck
